spring:
  profiles: default

zuul:
  routes:
    employee:
      path: /employee/**
      url: http://localhost:8083/employee
      service-id: /employee/**

    attendance:
      path: /attendance/**
      url: http://localhost:8081/attendance
      service-id: /attendance/**

    salary:
      path: /salary/**
      url: http://localhost:8082/salary
      service-id: /salary/**
